---
title: "Tables"
author: "Phong D. Nguyen"
date: "3/10/2022"
output: html_document
knit: (function(inputFile, encoding) {
  outDir <- 'docs';
  rmarkdown::render(inputFile, 
                    encoding=encoding,
                    output_file=file.path(dirname(inputFile), outDir, 'index.html'))})
---

<hr/>

The data set is of McDonald's full menu and was retrieved from kaggle.com. I simply want to provide the menu data in tabular form that can be searched and filtered for specific information. The header is styled different form the rest of the table to clearly display column information. 

```{r setup, include=FALSE}
library(knitr)
library(tidyverse)
library(DT)

#set chunk and figure default options
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE, tidy = TRUE)
```

```{r}
menu <- read_csv("data/menu.csv")

menu %>% datatable(
  caption = "McDonald's Food Menu", 
  options = list(
  initComplete = JS(
    "function(settings, json) {",
    "$(this.api().table().header()).css({'background-color': '#000', 'color': '#fff'});$('.main-container').css({'maxWidth': 'unset'})",
    "}")
))
```


<hr/>

## Appendix

```{r show-code, ref.label = all_labels(), echo = TRUE, eval = FALSE}
```